/* eslint-disable max-lines */

export const bookmarkDummyFolders = [
  { id: "1e892a923c7d4e9e", title: "Wind's Whispers", subtitle: "total hadith: 23", color: "#A3E4D7" },
  { id: "3a3d4f9e0c414b8f", title: "Missing Sock", subtitle: "total hadith: 23", color: "#F1948A" },
  { id: "5c9f87268729456e", title: "Dreamland", subtitle: "total hadith: 23", color: "#F7DC6F" },
  { id: "8b35f2c26e784b85", title: "Silence's Song", subtitle: "total hadith: 23", color: "#85C1E9" },
  { id: "0f9e35e11c8f4f2f", title: "Time Journey", subtitle: "total hadith: 23", color: "#BB8FCE" },
  { id: "b48e0d7f9a0b49a3", title: "Impossible Art", subtitle: "total hadith: 23", color: "#E59866" },
  { id: "d5f4c7e2b0a3495b", title: "Golden Key", subtitle: "total hadith: 23", color: "#58D68D" },
  { id: "e4a5f3c9d2b74f5e", title: "Everyday Magic", subtitle: "total hadith: 23", color: "#5499C7" },
  { id: "f2c58e6d6f2d4b8f", title: "Surface's Depth", subtitle: "total hadith: 23", color: "#DC7633" },
  { id: "6e8b7d8f7a5c3d2e", title: "Stars' Language", subtitle: "total hadith: 23", color: "#AF7AC5" },
  { id: "7f4e1a6b2c3d9a1e", title: "Belief's Power", subtitle: "total hadith: 23", color: "#5DADE2" },
  { id: "8e6f7b9c3a1b4f2e", title: "Color Symphony", subtitle: "total hadith: 23", color: "#F0B27A" },
  { id: "9d8c7e2b5f4a3d6f", title: "Unseen World", subtitle: "total hadith: 23", color: "#48C9B0" },
  { id: "a5e4b7d9f3c8a4e2", title: "Life's Rhythm", subtitle: "total hadith: 23", color: "#E74C3C" },
  { id: "b6f2d7c8a1e4b3d5", title: "Lost City", subtitle: "total hadith: 23", color: "#7FB3D5" },
  { id: "c7e5a4b9f2c8d3b7", title: "Happiness Quest", subtitle: "total hadith: 23", color: "#F5B041" },
  { id: "d8c7f2b5e4a6c3d8", title: "Infinite Glimpse", subtitle: "total hadith: 23", color: "#D35400" },
  { id: "e9f8d7c3b5a2e4f3", title: "Storytelling", subtitle: "total hadith: 23", color: "#F39C12" },
  { id: "f2a6b5c8e3d7f4b9", title: "Talking Cactus", subtitle: "total hadith: 23", color: "#85C1E9" },
  { id: "a4c7d8b5f2e6a3d9", title: "Dancing Stars", subtitle: "total hadith: 23", color: "#58D68D" },
  { id: "b3d5f4c7a9e8d2b6", title: "Whispers of Time", subtitle: "total hadith: 23", color: "#E74C3C" },
  { id: "c9e2f3a5d7b4c6f8", title: "Hidden Depths", subtitle: "total hadith: 23", color: "#A569BD" },
  { id: "d7f8b5e4c3a9f6b7", title: "Eternal Dance", subtitle: "total hadith: 23", color: "#F39C12" },
];

export const translationList = [
  {
    id: 1,
    name: "Sherif Ahmeti",
    lang: "albanian",
    locale: "sq",
    file_name: "albanian_ahmeti",
  },
  {
    id: 2,
    name: "Sadiq/Sani Habib",
    lang: "amharic",
    locale: "am",
    file_name: "amharic_sadiq",
  },
  {
    id: 3,
    name: "Shaykh Rafeequl Islam Habibur-Rahman",
    lang: "assamese",
    locale: "as",
    file_name: "as_rafeeq",
  },
  {
    id: 4,
    name: "Alikhan Musayev",
    lang: "azeri",
    locale: "az",
    file_name: "azerbaijani_musayev",
  },
  {
    id: 5,
    name: "Ahsanul Bayaan",
    lang: "bengali",
    locale: "bn",
    file_name: "bn_ahbayan",
  },
  {
    id: 6,
    name: "Fozlur Rahman",
    lang: "bengali",
    locale: "bn",
    file_name: "bn_fozlur",
  },
  {
    id: 7,
    name: "Muhiuddin Khan",
    lang: "bengali",
    locale: "bn",
    file_name: "bn_mkhan",
  },
  {
    id: 8,
    name: "Mujibur Rahman",
    lang: "bengali",
    locale: "bn",
    file_name: "bn_mujibur",
  },
  {
    id: 9,
    name: "Taisirul Quran",
    lang: "bengali",
    locale: "bn",
    file_name: "bn_taisirul",
  },
  {
    id: 10,
    name: "Dr. Abu Bakr Muhammad Zakaria",
    lang: "bengali",
    locale: "bn",
    file_name: "bn_zakaria",
  },
  {
    id: 11,
    name: "Besim Korkut",
    lang: "bosnian",
    locale: "bs",
    file_name: "bosnian_korkut",
  },
  {
    id: 12,
    name: "Muhammad Mihanovich",
    lang: "bosnian",
    locale: "bs",
    file_name: "bs_mihanovich",
  },
  {
    id: 13,
    name: "Ma Jian (Simplified)",
    lang: "chinese",
    locale: "zh",
    file_name: "chinese_jian",
  },
  {
    id: 14,
    name: "Ahmed Von Denffer",
    lang: "german",
    locale: "de",
    file_name: "de_denfer",
  },
  {
    id: 15,
    name: "Office of the President of Maldives",
    lang: "divehi",
    locale: "dv",
    file_name: "divehi_maldives",
  },
  {
    id: 16,
    name: "Salomo Keyzer",
    lang: "dutch",
    locale: "nl",
    file_name: "dutch_keyzer",
  },
  {
    id: 17,
    name: "Dr. Mustafa Khattab, the Clear Quran",
    lang: "english",
    locale: "en",
    file_name: "en_clear_quran",
  },
  {
    id: 18,
    name: "Abdul Haleem",
    lang: "english",
    locale: "en",
    file_name: "en_haleem",
  },
  {
    id: 19,
    name: "Tafsir Jalalayn",
    lang: "english",
    locale: "en",
    file_name: "en_jalalayn",
  },
  {
    id: 20,
    name: "Hilali and Khan",
    lang: "english",
    locale: "en",
    file_name: "en_khanhilali",
  },
  {
    id: 21,
    name: "Mufti Taqi Usmani",
    lang: "english",
    locale: "en",
    file_name: "en_muftitaqi",
  },
  {
    id: 22,
    name: "Pickthall",
    lang: "english",
    locale: "en",
    file_name: "en_pickthall",
  },
  {
    id: 23,
    name: "Saheeh International",
    lang: "english",
    locale: "en",
    file_name: "en_sahih",
  },
  {
    id: 24,
    name: "Transliteration",
    lang: "english",
    locale: "en",
    file_name: "en_transliteration",
  },
  {
    id: 25,
    name: "Abdullah Yusuf Ali",
    lang: "english",
    locale: "en",
    file_name: "en_yusufali",
  },
  {
    id: 26,
    name: "Julio Cortes",
    lang: "spanish",
    locale: "es",
    file_name: "es_cortes",
  },
  {
    id: 27,
    name: "Sheikh Isa Garcia",
    lang: "spanish",
    locale: "es",
    file_name: "es_garcia",
  },
  {
    id: 28,
    name: "Islamhouse",
    lang: "farsi",
    locale: "fa",
    file_name: "fa_islamhouse",
  },
  {
    id: 29,
    name: "Hussein Taji Kal Dari",
    lang: "farsi",
    locale: "fa",
    file_name: "farsi_husseintaji",
  },
  {
    id: 30,
    name: "Muhammad Hamidullah",
    lang: "french",
    locale: "fr",
    file_name: "french_hamid",
  },
  {
    id: 31,
    name: "Bubenheim/Elyas",
    lang: "german",
    locale: "de",
    file_name: "german_bubenheim",
  },
  {
    id: 32,
    name: "Abubakar Mahmoud Gumi",
    lang: "hausa",
    locale: "ha",
    file_name: "ha_mahmoud",
  },
  {
    id: 33,
    name: "Muhammad Farooq Khan",
    lang: "hindi",
    locale: "hi",
    file_name: "hindi_farooq",
  },
  {
    id: 34,
    name: "Syed Bilal Abdul Hai Hasani Nadwi",
    lang: "hindi",
    locale: "hi",
    file_name: "hindi_nadwi",
  },
  {
    id: 35,
    name: "Bahasa",
    lang: "indonesian",
    locale: "in",
    file_name: "in_bahasa",
  },
  {
    id: 36,
    name: "Tafsir Jalalayn",
    lang: "indonesian",
    locale: "in",
    file_name: "in_jalalayn",
  },
  {
    id: 37,
    name: "Hamza Roberto Piccardo",
    lang: "italian",
    locale: "it",
    file_name: "it_piccardo",
  },
  {
    id: 38,
    name: "Ryoichi Mita",
    lang: "japanese",
    locale: "ja",
    file_name: "ja_meta",
  },
  {
    id: 39,
    name: "Khalifah Altai",
    lang: "kazakh",
    locale: "kk",
    file_name: "kk_altai",
  },
  {
    id: 40,
    name: "Khalifah Altai Charity Foundation",
    lang: "kazakh",
    locale: "kk",
    file_name: "kk_altai_assoc",
  },
  {
    id: 41,
    name: "Cambodian Muslim Community Development",
    lang: "central khmer",
    locale: "km",
    file_name: "km_cambodia",
  },
  {
    id: 42,
    name: "Korean",
    lang: "korean",
    locale: "ko",
    file_name: "ko_korean",
  },
  {
    id: 43,
    name: "Burhan Muhammad Amin",
    lang: "kurdish",
    locale: "ku",
    file_name: "ku_asan",
  },
  {
    id: 44,
    name: "Muhammad Saleh Bamoki",
    lang: "kurdish",
    locale: "ku",
    file_name: "ku_bamoki",
  },
  {
    id: 45,
    name: "Abdul Hameed and Kunhi Mohammed",
    lang: "malayalam",
    locale: "ml",
    file_name: "ml_abdulhameed",
  },
  {
    id: 46,
    name: "Karakunnu/Elayavoor",
    lang: "malayalam",
    locale: "ml",
    file_name: "ml_karakunnu",
  },
  {
    id: 47,
    name: "So Quran al karim",
    lang: "maranao",
    locale: "mrn",
    file_name: "mrn_soquran",
  },
  {
    id: 48,
    name: "Abdullah Muhammad Basmeih",
    lang: "malay",
    locale: "ms",
    file_name: "ms_basmeih",
  },
  {
    id: 49,
    name: "Islami Sangh Nepal",
    lang: "nepali",
    locale: "ne",
    file_name: "ne_islamicsangh",
  },
  {
    id: 50,
    name: "Malak Faris Abdalsalaam",
    lang: "dutch",
    locale: "nl",
    file_name: "nl_abdalsalaam",
  },
  {
    id: 51,
    name: "Sofian S. Siregar",
    lang: "dutch",
    locale: "nl",
    file_name: "nl_siregar",
  },
  {
    id: 52,
    name: "Ghali Apapur Apaghuna",
    lang: "oromo",
    locale: "om",
    file_name: "om_ababor",
  },
  {
    id: 53,
    name: "Abdul Wali Khan",
    lang: "pashto",
    locale: "ps",
    file_name: "ps_abdulwali",
  },
  {
    id: 54,
    name: "Zakaria Abulsalam",
    lang: "pashto",
    locale: "ps",
    file_name: "ps_zakaria",
  },
  {
    id: 55,
    name: "Samir El Hayek",
    lang: "portuguese",
    locale: "pt",
    file_name: "pt_hayek",
  },
  {
    id: 56,
    name: "Abu Adel",
    lang: "russian",
    locale: "ru",
    file_name: "ru_abuadel",
  },
  {
    id: 57,
    name: "lmir Kuliev",
    lang: "russian",
    locale: "ru",
    file_name: "ru_kuliev",
  },
  {
    id: 58,
    name: "Taj Mehmood Amroti",
    lang: "sindhi",
    locale: "sd",
    file_name: "sd_amroti",
  },
  {
    id: 59,
    name: "Translation of the meanings of the 'Noble Qur'an",
    lang: "sinhala",
    locale: "si",
    file_name: "si_mahir",
  },
  {
    id: 60,
    name: "Mahmud Muhammad Abduh",
    lang: "somali",
    locale: "so",
    file_name: "so_abduh",
  },
  {
    id: 61,
    name: "Hassan Efendi Nahi",
    lang: "albanian",
    locale: "sq",
    file_name: "sq_nahi",
  },
  {
    id: 62,
    name: "Mohammed Knut Bernstrom",
    lang: "swedish",
    locale: "sv",
    file_name: "sv_bernstrom",
  },
  {
    id: 63,
    name: "Ali Muhsin Al-Barwani",
    lang: "swahili",
    locale: "sw",
    file_name: "sw_barwani",
  },
  {
    id: 64,
    name: "Abdul Hameed Baqavi",
    lang: "tamil",
    locale: "ta",
    file_name: "ta_baqavi",
  },
  {
    id: 65,
    name: "Jan Trust Foundation",
    lang: "tamil",
    locale: "ta",
    file_name: "ta_jantrust",
  },
  {
    id: 66,
    name: "Mufti Omar Sheriff Qasimi, Darul Huda",
    lang: "tamil",
    locale: "ta",
    file_name: "ta_omar_sheriff",
  },
  {
    id: 67,
    name: "Divya Quran Sandesham",
    lang: "telegu",
    locale: "te",
    file_name: "te_divya",
  },
  {
    id: 68,
    name: "Arifi",
    lang: "tajik",
    locale: "tg",
    file_name: "tg_arifi",
  },
  {
    id: 69,
    name: "King Fahad Quran Complex",
    lang: "thailand",
    locale: "th",
    file_name: "th_fahad",
  },
  {
    id: 70,
    name: "Al-QUR' N Al-Kareem (ICDO-KSA)",
    lang: "filipino",
    locale: "tl",
    file_name: "tl_icdo",
  },
  {
    id: 71,
    name: "The Quran Translation (Salas & Taron)",
    lang: "filipino",
    locale: "tl",
    file_name: "tl_salas_taron",
  },
  {
    id: 72,
    name: "Diyanet Isleri",
    lang: "turkish",
    locale: "tr",
    file_name: "tr_diyanet",
  },
  {
    id: 73,
    name: "Rowwad Tanslation Center",
    lang: "turkish",
    locale: "tr",
    file_name: "tr_rwwad",
  },
  {
    id: 74,
    name: "Shaban Britch",
    lang: "turkish",
    locale: "tr",
    file_name: "tr_shaban",
  },
  {
    id: 75,
    name: "Muslim Shahin",
    lang: "turkish",
    locale: "tr",
    file_name: "tr_shahin",
  },
  {
    id: 76,
    name: "Elmalili Hamdi Yazir",
    lang: "turkish",
    locale: "tr",
    file_name: "tr_yazir",
  },
  {
    id: 77,
    name: "Muhammad Saleh",
    lang: "uyghur",
    locale: "ug",
    file_name: "ug_saleh",
  },
  {
    id: 78,
    name: "Muhammad Junagarhi",
    lang: "urdu",
    locale: "ur",
    file_name: "ur_junagarhi",
  },
  {
    id: 79,
    name: "Alauddin Mansour",
    lang: "uzbek",
    locale: "uz",
    file_name: "uz_mansour",
  },
  {
    id: 80,
    name: "Muhammad Sodik Muhammad Yusuf",
    lang: "uzbek",
    locale: "uz",
    file_name: "uz_yusuf",
  },
  {
    id: 81,
    name: "Translation of Qur'an",
    lang: "yoruba",
    locale: "yo",
    file_name: "yo_mikail",
  },
];

interface Tafsir {
  name: string;
  lang: string;
  value: string;
}

export const tafsirObjectList: Record<string, Tafsir> = {
  ar_ibnkathir: { name: "Ibn Kathir (AR)", lang: "ar", value: "ar_ibnkathir" },
  ar_sa3dy: { name: "Sa'di (AR)", lang: "ar", value: "ar_sa3dy" },
  bn_fmazid: { name: "Fazlul Karim (BN)", lang: "bn", value: "bn_fmazid" },
  bn_kathir: { name: "Ibn Kathir (BN)", lang: "bn", value: "bn_kathir" },
  bn_zakaria: { name: "Zakaria (BN)", lang: "bn", value: "bn_zakaria" },
  en_kathir: { name: "Ibn Kathir (EN)", lang: "en", value: "en_kathir" },
  ru_sa3dy: { name: "Sa'di (RU)", lang: "ru", value: "ru_sa3dy" },
};

export const tafsirList = Object.values(tafsirObjectList);
