/* eslint-disable max-lines */
export const surahList = [
  {
    id: 1,
    place: "Makkah",
    bis_pre: 0,
    name: "Al-Fatihah",
    count: 7,
    pages: "[1,1]",
    trans_en: "The Opener",
    trans_bn: "সূচনা",
  },
  {
    id: 2,
    place: "Madinah",
    bis_pre: 1,
    name: "Al-Baqarah",
    count: 286,
    pages: "[2,49]",
    trans_en: "The Cow",
    trans_bn: "বকনা-বাছুর",
  },
  {
    id: 3,
    place: "Madinah",
    bis_pre: 1,
    name: "Ali 'Imran",
    count: 200,
    pages: "[50,76]",
    trans_en: "Family of Imran",
    trans_bn: "ইমরানের পরিবার",
  },
  {
    id: 4,
    place: "Madinah",
    bis_pre: 1,
    name: "An-Nisa",
    count: 176,
    pages: "[77,106]",
    trans_en: "The Women",
    trans_bn: "নারী",
  },
  {
    id: 5,
    place: "Madinah",
    bis_pre: 1,
    name: "Al-Ma'idah",
    count: 120,
    pages: "[106,127]",
    trans_en: "The Table Spread",
    trans_bn: "খাদ্য পরিবেশিত টেবিল",
  },
  {
    id: 6,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-An'am",
    count: 165,
    pages: "[128,150]",
    trans_en: "The Cattle",
    trans_bn: "গৃহপালিত পশু",
  },
  {
    id: 7,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-A'raf",
    count: 206,
    pages: "[151,176]",
    trans_en: "The Heights",
    trans_bn: "উচু স্থান",
  },
  {
    id: 8,
    place: "Madinah",
    bis_pre: 1,
    name: "Al-Anfal",
    count: 75,
    pages: "[177,186]",
    trans_en: "The Spoils of War",
    trans_bn: "যুদ্ধ-লব্ধ ধনসম্পদ",
  },
  {
    id: 9,
    place: "Madinah",
    bis_pre: 0,
    name: "At-Tawbah",
    count: 129,
    pages: "[187,207]",
    trans_en: "The Repentance",
    trans_bn: "অনুশোচনা",
  },
  {
    id: 10,
    place: "Makkah",
    bis_pre: 1,
    name: "Yunus",
    count: 109,
    pages: "[208,221]",
    trans_en: "Jonah",
    trans_bn: "নবী ইউনুস",
  },
  {
    id: 11,
    place: "Makkah",
    bis_pre: 1,
    name: "Hud",
    count: 123,
    pages: "[221,235]",
    trans_en: "Hud",
    trans_bn: "নবী হুদ",
  },
  {
    id: 12,
    place: "Makkah",
    bis_pre: 1,
    name: "Yusuf",
    count: 111,
    pages: "[235,248]",
    trans_en: "Joseph",
    trans_bn: "নবী ইউসুফ",
  },
  {
    id: 13,
    place: "Madinah",
    bis_pre: 1,
    name: "Ar-Ra'd",
    count: 43,
    pages: "[249,255]",
    trans_en: "The Thunder",
    trans_bn: "বজ্রপাত",
  },
  {
    id: 14,
    place: "Makkah",
    bis_pre: 1,
    name: "Ibrahim",
    count: 52,
    pages: "[255,261]",
    trans_en: "Abraham",
    trans_bn: "নবী ইবরাহীম",
  },
  {
    id: 15,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Hijr",
    count: 99,
    pages: "[262,267]",
    trans_en: "The Rocky Tract",
    trans_bn: "পাথুরে পাহাড়",
  },
  {
    id: 16,
    place: "Makkah",
    bis_pre: 1,
    name: "An-Nahl",
    count: 128,
    pages: "[267,281]",
    trans_en: "The Bee",
    trans_bn: "মৌমাছি",
  },
  {
    id: 17,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Isra",
    count: 111,
    pages: "[282,293]",
    trans_en: "The Night Journey",
    trans_bn: "ইহুদি জাতি",
  },
  {
    id: 18,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Kahf",
    count: 110,
    pages: "[293,304]",
    trans_en: "The Cave",
    trans_bn: "গুহা",
  },
  {
    id: 19,
    place: "Makkah",
    bis_pre: 1,
    name: "Maryam",
    count: 98,
    pages: "[305,312]",
    trans_en: "Mary",
    trans_bn: "মারইয়াম (ঈসা নবীর মা)",
  },
  {
    id: 20,
    place: "Makkah",
    bis_pre: 1,
    name: "Taha",
    count: 135,
    pages: "[312,321]",
    trans_en: "Ta-Ha",
    trans_bn: "ত়া হা",
  },
  {
    id: 21,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Anbya",
    count: 112,
    pages: "[322,331]",
    trans_en: "The Prophets",
    trans_bn: "নবীগণ",
  },
  {
    id: 22,
    place: "Madinah",
    bis_pre: 1,
    name: "Al-Hajj",
    count: 78,
    pages: "[332,341]",
    trans_en: "The Pilgrimage",
    trans_bn: "হ়াজ্জ",
  },
  {
    id: 23,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Mu'minun",
    count: 118,
    pages: "[342,349]",
    trans_en: "The Believers",
    trans_bn: "বিশ্বাসী",
  },
  {
    id: 24,
    place: "Madinah",
    bis_pre: 1,
    name: "An-Nur",
    count: 64,
    pages: "[350,359]",
    trans_en: "The Light",
    trans_bn: "আলো",
  },
  {
    id: 25,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Furqan",
    count: 77,
    pages: "[359,366]",
    trans_en: "The Criterion",
    trans_bn: "মানদণ্ড",
  },
  {
    id: 26,
    place: "Makkah",
    bis_pre: 1,
    name: "Ash-Shu'ara",
    count: 227,
    pages: "[367,376]",
    trans_en: "The Poets",
    trans_bn: "কবি",
  },
  {
    id: 27,
    place: "Makkah",
    bis_pre: 1,
    name: "An-Naml",
    count: 93,
    pages: "[377,385]",
    trans_en: "The Ant",
    trans_bn: "পিঁপড়া",
  },
  {
    id: 28,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Qasas",
    count: 88,
    pages: "[385,396]",
    trans_en: "The Stories",
    trans_bn: "কাহিনি",
  },
  {
    id: 29,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-'Ankabut",
    count: 69,
    pages: "[396,404]",
    trans_en: "The Spider",
    trans_bn: "মাকড়শা",
  },
  {
    id: 30,
    place: "Makkah",
    bis_pre: 1,
    name: "Ar-Rum",
    count: 60,
    pages: "[404,410]",
    trans_en: "The Romans",
    trans_bn: "রোমান জাতি",
  },
  {
    id: 31,
    place: "Makkah",
    bis_pre: 1,
    name: "Luqman",
    count: 34,
    pages: "[411,414]",
    trans_en: "Luqman",
    trans_bn: "এক জ্ঞানী ব্যাক্তি",
  },
  {
    id: 32,
    place: "Makkah",
    bis_pre: 1,
    name: "As-Sajdah",
    count: 30,
    pages: "[415,417]",
    trans_en: "The Prostration",
    trans_bn: "সিজদা",
  },
  {
    id: 33,
    place: "Madinah",
    bis_pre: 1,
    name: "Al-Ahzab",
    count: 73,
    pages: "[418,427]",
    trans_en: "The Combined Forces",
    trans_bn: "জোট",
  },
  {
    id: 34,
    place: "Makkah",
    bis_pre: 1,
    name: "Saba",
    count: 54,
    pages: "[428,434]",
    trans_en: "Sheba",
    trans_bn: "রানী সাবা/শেবা",
  },
  {
    id: 35,
    place: "Makkah",
    bis_pre: 1,
    name: "Fatir",
    count: 45,
    pages: "[434,440]",
    trans_en: "Originator",
    trans_bn: "আদি স্রষ্টা",
  },
  {
    id: 36,
    place: "Makkah",
    bis_pre: 1,
    name: "Ya-Sin",
    count: 83,
    pages: "[440,445]",
    trans_en: "Ya Sin",
    trans_bn: "ইয়াসীন",
  },
  {
    id: 37,
    place: "Makkah",
    bis_pre: 1,
    name: "As-Saffat",
    count: 182,
    pages: "[446,452]",
    trans_en: "Those who set the Ranks",
    trans_bn: "সারিবদ্ধভাবে দাঁড়ানো",
  },
  {
    id: 38,
    place: "Makkah",
    bis_pre: 1,
    name: "Sad",
    count: 88,
    pages: "[453,458]",
    trans_en: 'The Letter "Saad"',
    trans_bn: "আরবি বর্ণ সাদ",
  },
  {
    id: 39,
    place: "Makkah",
    bis_pre: 1,
    name: "Az-Zumar",
    count: 75,
    pages: "[458,467]",
    trans_en: "The Troops",
    trans_bn: "দলবদ্ধ জনতা",
  },
  {
    id: 40,
    place: "Makkah",
    bis_pre: 1,
    name: "Ghafir",
    count: 85,
    pages: "[467,476]",
    trans_en: "The Forgiver",
    trans_bn: "ক্ষমাকারী",
  },
  {
    id: 41,
    place: "Makkah",
    bis_pre: 1,
    name: "Fussilat",
    count: 54,
    pages: "[477,482]",
    trans_en: "Explained in Detail",
    trans_bn: "সুস্পষ্ট বিবরণ",
  },
  {
    id: 42,
    place: "Makkah",
    bis_pre: 1,
    name: "Ash-Shuraa",
    count: 53,
    pages: "[483,489]",
    trans_en: "The Consultation",
    trans_bn: "পরামর্শ",
  },
  {
    id: 43,
    place: "Makkah",
    bis_pre: 1,
    name: "Az-Zukhruf",
    count: 89,
    pages: "[489,495]",
    trans_en: "The Ornaments of Gold",
    trans_bn: "সোনাদানা",
  },
  {
    id: 44,
    place: "Makkah",
    bis_pre: 1,
    name: "Ad-Dukhan",
    count: 59,
    pages: "[496,498]",
    trans_en: "The Smoke",
    trans_bn: "ধোঁয়া",
  },
  {
    id: 45,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Jathiyah",
    count: 37,
    pages: "[499,502]",
    trans_en: "The Crouching",
    trans_bn: "নতজানু",
  },
  {
    id: 46,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Ahqaf",
    count: 35,
    pages: "[502,506]",
    trans_en: "The Wind-Curved Sandhills",
    trans_bn: "বালুর পাহাড়",
  },
  {
    id: 47,
    place: "Madinah",
    bis_pre: 1,
    name: "Muhammad",
    count: 38,
    pages: "[507,510]",
    trans_en: "Muhammad",
    trans_bn: "নবী মুহাম্মদ",
  },
  {
    id: 48,
    place: "Madinah",
    bis_pre: 1,
    name: "Al-Fath",
    count: 29,
    pages: "[511,515]",
    trans_en: "The Victory",
    trans_bn: "বিজয়",
  },
  {
    id: 49,
    place: "Madinah",
    bis_pre: 1,
    name: "Al-Hujurat",
    count: 18,
    pages: "[515,517]",
    trans_en: "The Rooms",
    trans_bn: "আবাস",
  },
  {
    id: 50,
    place: "Makkah",
    bis_pre: 1,
    name: "Qaf",
    count: 45,
    pages: "[518,520]",
    trans_en: 'The Letter "Qaf"',
    trans_bn: "কাফ",
  },
  {
    id: 51,
    place: "Makkah",
    bis_pre: 1,
    name: "Adh-Dhariyat",
    count: 60,
    pages: "[520,523]",
    trans_en: "The Winnowing Winds",
    trans_bn: "বিক্ষেপকারী বাতাস",
  },
  {
    id: 52,
    place: "Makkah",
    bis_pre: 1,
    name: "At-Tur",
    count: 49,
    pages: "[523,525]",
    trans_en: "The Mount",
    trans_bn: "পাহাড়",
  },
  {
    id: 53,
    place: "Makkah",
    bis_pre: 1,
    name: "An-Najm",
    count: 62,
    pages: "[526,528]",
    trans_en: "The Star",
    trans_bn: "তারা",
  },
  {
    id: 54,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Qamar",
    count: 55,
    pages: "[528,531]",
    trans_en: "The Moon",
    trans_bn: "চাঁদ",
  },
  {
    id: 55,
    place: "Madinah",
    bis_pre: 1,
    name: "Ar-Rahman",
    count: 78,
    pages: "[531,534]",
    trans_en: "The Beneficent",
    trans_bn: "পরম করুণাময়",
  },
  {
    id: 56,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Waqi'ah",
    count: 96,
    pages: "[534,537]",
    trans_en: "The Inevitable",
    trans_bn: "নিশ্চিত ঘটনা",
  },
  {
    id: 57,
    place: "Madinah",
    bis_pre: 1,
    name: "Al-Hadid",
    count: 29,
    pages: "[537,541]",
    trans_en: "The Iron",
    trans_bn: "লোহা",
  },
  {
    id: 58,
    place: "Madinah",
    bis_pre: 1,
    name: "Al-Mujadila",
    count: 22,
    pages: "[542,545]",
    trans_en: "The Pleading Woman",
    trans_bn: "অনুযোগকারিণী",
  },
  {
    id: 59,
    place: "Madinah",
    bis_pre: 1,
    name: "Al-Hashr",
    count: 24,
    pages: "[545,548]",
    trans_en: "The Exile",
    trans_bn: "সমাবেশ",
  },
  {
    id: 60,
    place: "Madinah",
    bis_pre: 1,
    name: "Al-Mumtahanah",
    count: 13,
    pages: "[549,551]",
    trans_en: "She that is to be examined",
    trans_bn: "নারী, যাকে পরীক্ষা করা হবে",
  },
  {
    id: 61,
    place: "Madinah",
    bis_pre: 1,
    name: "As-Saf",
    count: 14,
    pages: "[551,552]",
    trans_en: "The Ranks",
    trans_bn: "সারিবদ্ধ সৈন্যদল",
  },
  {
    id: 62,
    place: "Madinah",
    bis_pre: 1,
    name: "Al-Jumu'ah",
    count: 11,
    pages: "[553,554]",
    trans_en: "The Congregation, Friday",
    trans_bn: "সম্মেলন/শুক্রবার",
  },
  {
    id: 63,
    place: "Madinah",
    bis_pre: 1,
    name: "Al-Munafiqun",
    count: 11,
    pages: "[554,555]",
    trans_en: "The Hypocrites",
    trans_bn: "ভণ্ড বিশ্বাসী",
  },
  {
    id: 64,
    place: "Madinah",
    bis_pre: 1,
    name: "At-Taghabun",
    count: 18,
    pages: "[556,557]",
    trans_en: "The Mutual Disillusion",
    trans_bn: "মোহ অপসারণ",
  },
  {
    id: 65,
    place: "Madinah",
    bis_pre: 1,
    name: "At-Talaq",
    count: 12,
    pages: "[558,559]",
    trans_en: "The Divorce",
    trans_bn: "তালাক",
  },
  {
    id: 66,
    place: "Madinah",
    bis_pre: 1,
    name: "At-Tahrim",
    count: 12,
    pages: "[560,561]",
    trans_en: "The Prohibition",
    trans_bn: "নিষিদ্ধকরণ",
  },
  {
    id: 67,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Mulk",
    count: 30,
    pages: "[562,564]",
    trans_en: "The Sovereignty",
    trans_bn: "সার্বভৌম কর্তৃত্ব",
  },
  {
    id: 68,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Qalam",
    count: 52,
    pages: "[564,566]",
    trans_en: "The Pen",
    trans_bn: "কলম",
  },
  {
    id: 69,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Haqqah",
    count: 52,
    pages: "[566,568]",
    trans_en: "The Reality",
    trans_bn: "নিশ্চিত সত্য",
  },
  {
    id: 70,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Ma'arij",
    count: 44,
    pages: "[568,570]",
    trans_en: "The Ascending Stairways",
    trans_bn: "উন্নয়নের সোপান",
  },
  {
    id: 71,
    place: "Makkah",
    bis_pre: 1,
    name: "Nuh",
    count: 28,
    pages: "[570,571]",
    trans_en: "Noah",
    trans_bn: "নবী নূহ",
  },
  {
    id: 72,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Jinn",
    count: 28,
    pages: "[572,573]",
    trans_en: "The Jinn",
    trans_bn: "জিন সম্প্রদায়",
  },
  {
    id: 73,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Muzzammil",
    count: 20,
    pages: "[574,575]",
    trans_en: "The Enshrouded One",
    trans_bn: "বস্ত্রাচ্ছাদনকারী",
  },
  {
    id: 74,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Muddaththir",
    count: 56,
    pages: "[575,577]",
    trans_en: "The Cloaked One",
    trans_bn: "পোশাক পরিহিত",
  },
  {
    id: 75,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Qiyamah",
    count: 40,
    pages: "[577,578]",
    trans_en: "The Resurrection",
    trans_bn: "পুনরুত্থান",
  },
  {
    id: 76,
    place: "Madinah",
    bis_pre: 1,
    name: "Al-Insan",
    count: 31,
    pages: "[578,580]",
    trans_en: "The Man",
    trans_bn: "মানবজাতি",
  },
  {
    id: 77,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Mursalat",
    count: 50,
    pages: "[580,581]",
    trans_en: "The Emissaries",
    trans_bn: "প্রেরিত পুরুষ",
  },
  {
    id: 78,
    place: "Makkah",
    bis_pre: 1,
    name: "An-Naba",
    count: 40,
    pages: "[582,583]",
    trans_en: "The Tidings",
    trans_bn: "মহাসংবাদ",
  },
  {
    id: 79,
    place: "Makkah",
    bis_pre: 1,
    name: "An-Nazi'at",
    count: 46,
    pages: "[583,584]",
    trans_en: "Those who drag forth",
    trans_bn: "প্রচেষ্টাকারী",
  },
  {
    id: 80,
    place: "Makkah",
    bis_pre: 1,
    name: "Abasa",
    count: 42,
    pages: "[585,585]",
    trans_en: "He Frowned",
    trans_bn: "সে ভ্রু কুঁচকালো",
  },
  {
    id: 81,
    place: "Makkah",
    bis_pre: 1,
    name: "At-Takwir",
    count: 29,
    pages: "[586,586]",
    trans_en: "The Overthrowing",
    trans_bn: "অন্ধকারাচ্ছন্ন",
  },
  {
    id: 82,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Infitar",
    count: 19,
    pages: "[587,587]",
    trans_en: "The Cleaving",
    trans_bn: "বিদীর্ণ করা",
  },
  {
    id: 83,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Mutaffifin",
    count: 36,
    pages: "[587,589]",
    trans_en: "The Defrauding",
    trans_bn: "প্রতারণা করা",
  },
  {
    id: 84,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Inshiqaq",
    count: 25,
    pages: "[589,589]",
    trans_en: "The Sundering",
    trans_bn: "খণ্ড-বিখণ্ডকরণ",
  },
  {
    id: 85,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Buruj",
    count: 22,
    pages: "[590,590]",
    trans_en: "The Mansions of the Stars",
    trans_bn: "নক্ষত্রপুঞ্জ",
  },
  {
    id: 86,
    place: "Makkah",
    bis_pre: 1,
    name: "At-Tariq",
    count: 17,
    pages: "[591,591]",
    trans_en: "The Nightcommer",
    trans_bn: "রাতের আগন্তুক",
  },
  {
    id: 87,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-A'la",
    count: 19,
    pages: "[591,592]",
    trans_en: "The Most High",
    trans_bn: "সর্বোন্নত",
  },
  {
    id: 88,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Ghashiyah",
    count: 26,
    pages: "[592,592]",
    trans_en: "The Overwhelming",
    trans_bn: "বিহ্বলকর ঘটনা",
  },
  {
    id: 89,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Fajr",
    count: 30,
    pages: "[593,594]",
    trans_en: "The Dawn",
    trans_bn: "ভোরবেলা",
  },
  {
    id: 90,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Balad",
    count: 20,
    pages: "[594,594]",
    trans_en: "The City",
    trans_bn: "নগর",
  },
  {
    id: 91,
    place: "Makkah",
    bis_pre: 1,
    name: "Ash-Shams",
    count: 15,
    pages: "[595,595]",
    trans_en: "The Sun",
    trans_bn: "সূর্য",
  },
  {
    id: 92,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Layl",
    count: 21,
    pages: "[595,596]",
    trans_en: "The Night",
    trans_bn: "রাত",
  },
  {
    id: 93,
    place: "Makkah",
    bis_pre: 1,
    name: "Ad-Duhaa",
    count: 11,
    pages: "[596,596]",
    trans_en: "The Morning Hours",
    trans_bn: "পূর্বাহ্নের সুর্যকিরণ",
  },
  {
    id: 94,
    place: "Makkah",
    bis_pre: 1,
    name: "Ash-Sharh",
    count: 8,
    pages: "[596,596]",
    trans_en: "The Relief",
    trans_bn: "বক্ষ প্রশস্তকরণ",
  },
  {
    id: 95,
    place: "Makkah",
    bis_pre: 1,
    name: "At-Tin",
    count: 8,
    pages: "[597,597]",
    trans_en: "The Fig",
    trans_bn: "ডুমুর",
  },
  {
    id: 96,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-'Alaq",
    count: 19,
    pages: "[597,597]",
    trans_en: "The Clot",
    trans_bn: "রক্তপিণ্ড",
  },
  {
    id: 97,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Qadr",
    count: 5,
    pages: "[598,598]",
    trans_en: "The Power",
    trans_bn: "মহিমান্বিত",
  },
  {
    id: 98,
    place: "Madinah",
    bis_pre: 1,
    name: "Al-Bayyinah",
    count: 8,
    pages: "[598,599]",
    trans_en: "The Clear Proof",
    trans_bn: "প্রমাণ",
  },
  {
    id: 99,
    place: "Madinah",
    bis_pre: 1,
    name: "Az-Zalzalah",
    count: 8,
    pages: "[599,599]",
    trans_en: "The Earthquake",
    trans_bn: "ভূমিকম্প",
  },
  {
    id: 100,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-'Adiyat",
    count: 11,
    pages: "[599,600]",
    trans_en: "The Courser",
    trans_bn: "অভিযানকারী",
  },
  {
    id: 101,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Qari'ah",
    count: 11,
    pages: "[600,600]",
    trans_en: "The Calamity",
    trans_bn: "মহাসংকট",
  },
  {
    id: 102,
    place: "Makkah",
    bis_pre: 1,
    name: "At-Takathur",
    count: 8,
    pages: "[600,600]",
    trans_en: "The Rivalry in world increase",
    trans_bn: "প্রাচুর্যের প্রতিযোগিতা",
  },
  {
    id: 103,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-'Asr",
    count: 3,
    pages: "[601,601]",
    trans_en: "The Declining Day",
    trans_bn: "সময়",
  },
  {
    id: 104,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Humazah",
    count: 9,
    pages: "[601,601]",
    trans_en: "The Traducer",
    trans_bn: "পরনিন্দাকারী",
  },
  {
    id: 105,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Fil",
    count: 5,
    pages: "[601,601]",
    trans_en: "The Elephant",
    trans_bn: "হাতি",
  },
  {
    id: 106,
    place: "Makkah",
    bis_pre: 1,
    name: "Quraysh",
    count: 4,
    pages: "[602,602]",
    trans_en: "Quraysh",
    trans_bn: "কুরাইশ গোত্র",
  },
  {
    id: 107,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Ma'un",
    count: 7,
    pages: "[602,602]",
    trans_en: "The Small kindnesses",
    trans_bn: "সাহায্য সহায়তা",
  },
  {
    id: 108,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Kawthar",
    count: 3,
    pages: "[602,602]",
    trans_en: "The Abundance",
    trans_bn: "কাউসার/প্রাচুর্য",
  },
  {
    id: 109,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Kafirun",
    count: 6,
    pages: "[603,603]",
    trans_en: "The Disbelievers",
    trans_bn: "অবিশ্বাসী",
  },
  {
    id: 110,
    place: "Madinah",
    bis_pre: 1,
    name: "An-Nasr",
    count: 3,
    pages: "[603,603]",
    trans_en: "The Divine Support",
    trans_bn: "সাহায্য",
  },
  {
    id: 111,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Masad",
    count: 5,
    pages: "[603,603]",
    trans_en: "The Palm Fiber",
    trans_bn: "খেজুরের পাকানো (রশি)",
  },
  {
    id: 112,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Ikhlas",
    count: 4,
    pages: "[604,604]",
    trans_en: "The Sincerity",
    trans_bn: "আন্তরিকতা",
  },
  {
    id: 113,
    place: "Makkah",
    bis_pre: 1,
    name: "Al-Falaq",
    count: 5,
    pages: "[604,604]",
    trans_en: "The Daybreak",
    trans_bn: "নিশিভোর",
  },
  {
    id: 114,
    place: "Makkah",
    bis_pre: 1,
    name: "An-Nas",
    count: 6,
    pages: "[604,604]",
    trans_en: "Mankind",
    trans_bn: "মানুষ জাতি",
  },
];
