name: Deploy quranmazid frontend to oracle cloud

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Zip
        run: |
          zip -r frontend.zip . -x "node_modules/*" ".git/*" ".github/*"
          ls -l frontend.zip -h

      - name: Copy the zip file to Oracle Cloud
        env:
          OCI_HOST: ${{ secrets.OCI_HOST }}
          OCI_KEY: ${{ secrets.OCI_KEY }}
        run: |
          echo "$OCI_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          ssh -o StrictHostKeyChecking=no -i deploy_key.pem ubuntu@$OCI_HOST 'sudo mkdir -p /var/www/quran-mazid/frontend && sudo chown -R ubuntu:ubuntu /var/www/quran-mazid'
          scp -o StrictHostKeyChecking=no -i deploy_key.pem frontend.zip ubuntu@$OCI_HOST:/var/www/quran-mazid/frontend/

      - name: SSH into Oracle Cloud and deploy
        env:
          OCI_HOST: ${{ secrets.OCI_HOST }}
          OCI_KEY: ${{ secrets.OCI_KEY }}
        run: |
          echo "$OCI_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          ssh -o StrictHostKeyChecking=no -i deploy_key.pem ubuntu@$OCI_HOST << 'EOF'
            cd /var/www/quran-mazid/frontend
            unzip -o /var/www/quran-mazid/frontend/frontend.zip
            npm i
            if pm2 list | grep -q quran-frontend; then
              pm2 restart quran-frontend
            else
              pm2 start npm --name quran-frontend -- run start
            fi
          EOF
